import axios from "../../lib"
export default{
    conGetData({commit}){
        axios({
            method:"get",
            url:"/api/mock/5c346519fad511025643ee90/example/dynamic"
        }).then((data)=>{
            console.log(data.data.concern)
            commit("conGetData",data.data.concern)
        })
    },
    recGetData({commit}){
        axios({
            method:"get",
            url:"/api/mock/5c346519fad511025643ee90/example/dynamic"
        }).then((data)=>{
            console.log(data.data.concern)
            commit("recGetData",data.data.concern)
        })
    },
    neaGetData({commit}){
        axios({
            method:"get",
            url:"/api/mock/5c346519fad511025643ee90/example/dynamic"
        }).then((data)=>{
            console.log(data.data.concern)
            commit("neaGetData",data.data.concern)
        })
    }
}